
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param code
     * @return
     *     returns ws.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws/", className = "ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws/", className = "ws.GetUserResponse")
    @Action(input = "http://ws/UserService/getUserRequest", output = "http://ws/UserService/getUserResponse")
    public User getUser(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param age
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBirthYear", targetNamespace = "http://ws/", className = "ws.GetBirthYear")
    @ResponseWrapper(localName = "getBirthYearResponse", targetNamespace = "http://ws/", className = "ws.GetBirthYearResponse")
    @Action(input = "http://ws/UserService/getBirthYearRequest", output = "http://ws/UserService/getBirthYearResponse")
    public int getBirthYear(
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @return
     *     returns java.util.List<ws.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://ws/", className = "ws.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://ws/", className = "ws.GetUserListResponse")
    @Action(input = "http://ws/UserService/getUserListRequest", output = "http://ws/UserService/getUserListResponse")
    public List<User> getUserList();

}
